---
version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrower
    user: 1000:1000
    ports:
      - 80:80
    volumes:
      - path/to:/srv
      - path/to/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true