---
version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrower
    user: 0:0
    ports:
      - 2333:80
    volumes:
      - /:/srv
      - /pkgtk/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true