---
version: '3'

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80
      - 443:443
      - 3000:3000
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_config:/opt/adguardhome/conf

volumes:
  adguard_data:
    name: adguard_data
  adguard_config:
    name: adguard_config