---
version: '3'

services:
  nginx:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    ports:
      #- 80:80
      - 81:81
      - 443:443
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: 'npm'
      DB_MYSQL_NAME: 'npm'
    volumes:
      - pkgtk/nginx-proxy-manager/data:/data
      - pkgtk/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
  db:
    container_name: ngnix-proxy-manager-db
    image: jc21/mariadb-aria:latest
    networks:
      - nginx-proxy-network
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /pkgtk/nginx-proxy-manager/data/mysql:/var/lib/mysql

networks:
  nginx-proxy-network:
    external: true
