---
version: '3'

services:
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: always
    ports:
      #- 80:80
      - 81:81
      - 443:443
    environment:
      DB_MYSQL_HOST: 'nginx_proxy_manager_db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_MYSQL_USER} # npm
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD} # npm
      DB_MYSQL_NAME: ${DB_MYSQL_NAME} # npm
      TP_THEME: ${TP_THEME} # dracula
      # DISABLE_IPV6: 'true'
      # DB_SQLITE_FILE: '/data/database.sqlite'
    volumes:
      - path/to/nginx_proxy_manager/data:/data
      - path/to/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
      # - path/to/nginx_proxy_manager/98-themepark:/etc/cont-init.d/99-themepark
    depends_on:
      - nginx_proxy_manager_db

  nginx_proxy_manager_db:
    image: mariadb:latest
    container_name: ngnix_proxy_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - path/to/nginx_proxy_manager/mysql:/var/lib/mysql

networks:
  default:
    external:
      name: network_name
