---
version: "3.5"

services:
  asf:
    image: justarchi/archisteamfarm
    container_name: archisteamfarm
    hostname: asf
    environment:
      - ASF_ARGS=--server
    networks:
      - fdn
    ports:
      - 1242:1242
    volumes:
      - /pkgtk/archisteamfarm/config:/app/config
      - /pkgtk/archisteamfarm/logs:/app/logs
      - /pkgtk/archisteamfarm/plugins:/app/plugins
    restart: always
  asfbot:
    image: dmcallejo/asfbot
    container_name: asfbot
    hostname: asfbot
    networks:
      - fdn
    restart: unless-stopped
    command: --host asf
    environment:
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_USER_ALIAS=
      - ASF_IPC_PASSWORD=
      - ASF_IPC_PORT=1242
      
networks:
  fdn:
    external: true
