---
version: '3'

services:
  archisteamfarm:
    image: justarchi/archisteamfarm:5.3.0.3
    container_name: archisteamfarm
    restart: unless-stopped
    ports:
      - 1242:1242
    volumes:
      - /path/to/archisteamfarm/config:/app/config
      - /path/to/archisteamfarm/logs:/app/logs
      - /path/to/archisteamfarm/plugins:/app/plugins

  asfbot:
    image: dmcallejo/asfbot
    container_name: asfbot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_USER_ALIAS: ${TELEGRAM_USER_ALIAS}
      ASF_IPC_PASSWORD: ${ASF_IPC_PASSWORD}
      ASF_IPC_PORT: ${ASF_IPC_PORT}
    depends_on:
      - archisteamfarm