---
version: "3.5"

services:
  asf:
    image: justarchi/archisteamfarm
    container_name: archisteamfarm
    hostname: asf
    environment:
      - ASF_ARGS=--server
    networks:
      - asf
    ports:
      - 1242:1242
    volumes:
      - ${ASF_DIR}/config:/app/config
      - ${ASF_DIR}/logs:/app/logs
      - ${ASF_DIR}/plugins:/app/plugins
    restart: always
  asfbot:
    image: dmcallejo/asfbot
    container_name: asfbot
    hostname: asfbot
    depends_on:
      - asf
    networks:
      - asf
    restart: unless-stopped
    command: --host asf
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_USER_ALIAS=${TELEGRAM_USER_ALIAS}
      - ASF_IPC_PASSWORD=${ASF_IPC_PASSWORD}
      - ASF_IPC_PORT=${ASF_IPC_PORT}
      
networks:
  asf: {}