---
version: '3'

services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader-2
    ports: 5800:5800
    restart: unless-stopped
    volumes:
      - /path/to/jdownloader-2:/config:rw
      - /path/to/Downloads:/output:rw