---
version: '3'

services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    ports:
     - 9000:9000
    volumes:
     - portainer_data:/data
     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
    name: portainer_data
