---
version: '3'

services:
  flood:
    image: jesec/flood
    container_name: flood
    restart: unless-stopped
    user: 1000:1001
    hostname: flood
    command: --port 3001 --allowedpath /data
    ports:
      - 3001:3001
    environment:
      HOME: /config
    volumes:
      - /path/to/flood/dlconfig:/config
      - /path/to/flood/data:/data