---
version: '3'

services:
  guacmole:
    image: oznu/guacamole
    container_name: guacamole
    restart: unless-stopped
    ports:
      - 7952:8080
    volumes:
      - /path/to/guacamole:/config