---
version: "3.5"

services:
  guacmole:
    image: oznu/guacamole
    container_name: guacmole
    networks:
      - dnr
    ports:
      - 7952:8080
    volumes:
      - /pkgtk/guacmole:/config
    restart: unless-stopped
    
networks:
  dnr:
    external: true