---
version: '3'

services:
  guacmole:
    image: oznu/guacamole
    container_name: guacmole
    ports:
      - 7952:8080
    volumes:
      - path/to/guacmole:/config
    restart: unless-stopped