---
version: '3'

services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    user: 1000:1000
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_DEFAULTTHEME: spotify-ish
      ND_ENABLEDOWNLOADS: true
      ND_ENABLECOVERANIMATION: true
    volumes:
      - /path/to/data:/data
      - /path/to/your/music/folder:/music:ro