---
version: '3'

services:
  pyload:
    image: lscr.io/linuxserver/pyload
    container_name: pyload
    restart: unless-stopped
    ports:
      - 8000:8000
      #- 7227:7227 #optional
    environment:
      PUID:1000
      PGID:1000
      TZ:Europe/London
    volumes:
      - /path/to/pyload/config:/config
      - /path/to/pyload/downloads:/downloads