---
version: "3.5"

services:
  archisteamfarm:
    image: justarchi/archisteamfarm
    container_name: archisteamfarm
    networks:
      - fnk
    ports:
     - "4862:1242"
    volumes:
     - /pkgtk/archisteamfarm/config:/app/config
     - /pkgtk/archisteamfarm/logs:/app/logs
     - /pkgtk/archisteamfarm/plugins:/app/plugins
    restart: always

networks:
  fnk:
    external: true
