version: "3.5"

services:
  portainer:
    image: portainer/portainer-ce
    ports:
     - "8001:8000"
     - "3322:9000"
    volumes:
     - portainer_1:/data
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
volumes:
  portainer_1:
