---
- hosts: #name
  tasks:

    - name: Deploying Portainer-Agent
      community.docker.docker_container:
        name: portainer-agent
        image: portainer/agent
        ports:
          - 9050:9001
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart_policy: always