---
version: '3'

services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      UID:1000
      GID:1000
    volumes:
      - /path/to/homer/assets/:/www/assets