---
version: '3'

services:
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    ports:
      - 1199:1194/udp
    volumes:
      - /opt/openvpn-data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      vpn-network:
        ipv4_address: 172.20.0.3

  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      # Uncomment port 80 if you want to have pihole UI
      - 888:80/tcp
      - 443:443/tcp
    environment:
      TZ: Europe/London
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      WEBPASSWORD: PASSWORD
    volumes:
       - /opt/pihole:/etc/pihole
       - /opt/pihole:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
       vpn-network:
         ipv4_address: 172.20.0.2

networks:
  vpn-network:
    external: true
