---
version: '3'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    restart: unless-stopped
    ports:
      - 1194:1194/udp
    volumes:
      - /path/to/openvpn:/etc/openvpn
    cap_add:
      - NET_ADMIN

  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      # Uncomment port 80 if you want to have pihole UI
      - 888:80/tcp
      - 443:443/tcp
    environment:
      TZ: Europe/London
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      WEBPASSWORD: PASSWORD
    volumes:
       - /path/to/pihole:/etc/pihole
       - /path/to/pihole:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
