---
version: "2.1"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /pkgtk/qBittorrent/config:/config
      - /pkgtk/qBittorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8686:8080
    restart: unless-stopped