---
version: "2.1"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID:1000
      - PGID:1000
      - TZ:Europe/London
      - WEBUI_PORT:8080
    volumes:
      - /path/to/qBittorrent/config:/config
      - /path/to/qBittorrent/downloads:/downloads