---
version: '3'

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      TZ: Europe/London
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      WEBPASSWORD: PASSWORD
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    volumes:
       - /path/to/pihole:/etc/pihole
       - /path/to/pihole:/etc/dnsmasq.d