---
version: '2.1'
services:
  filezilla:
    image: lscr.io/linuxserver/filezilla
    container_name: filezilla
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /pkgtk/filezilla/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped