---
version: '2.1'

services:
  filezilla:
    image: lscr.io/linuxserver/filezilla
    container_name: filezilla
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/filezilla/config:/config